### ISSUE TITLE
iphone: Configure button doesn't work when going back to a previous step

### ISSUE THREAD

**Issue by lavenal** [OpenLiberty/iguide-circuit-breaker#11] opened 2017-10-03 13:58 UTC
To recreate the problem using an iphone:
- follow the instruction to complete configuring failure threshold step
- click on next to go to configuring delay step
- click on previous to go back to configuring failure threshold step
- click on run tab icon
- click on the Configure button

**Comment by steven1046** [comment] 2017-10-03 19:17
This might be fixed by the fix in https://github.com/OpenLiberty/iguide-circuit-breaker/pull/24

**Comment by steven1046** [comment] 2017-10-04 14:13
Closed since we confirmed the fix for #24 fixed this issue also.

**Closed** 2017-10-04 14:13 UTC
Labels: bug
